apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-09-13T11:04:33Z"
  generation: 61
  name: kube-prometheus-stack
  namespace: argocd
  resourceVersion: "204590495"
  uid: 9bd1a2e0-fe40-4c71-a0ef-b000932ff7e6
spec:
  destination:
    namespace: prom-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: kube-prometheus
    helm:
      valueFiles:
      - $values/bitnami-kube-prom-values.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.5.15
  - ref: values
    repoURL: https://github.com/avk999/argocd
    targetRevision: HEAD
