apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  ignoreDifferences:
  - kind: Secret
    name: digitaloceanapi
  syncPolicy:
  project: default
  sources:
    - chart: cert-manager
      repoURL:  https://charts.bitnami.com/bitnami
      targetRevision: 1.3.21
      helm:
        values: |
          installCRDs: true
          metrics:
            serviceMonitor:
              enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
