apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: prom-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/prometheus-community-values.yaml
    repoURL:  https://prometheus-community.github.io/helm-charts
    targetRevision: 62.6.0
  - ref: values
    repoURL: https://github.com/avk999/argocd
    targetRevision: HEAD
