apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  finalizers: 
    - operator-sanity
spec:
  destination:
    name: 'promstack'
    namespace: prom-system
    server: https://kubernetes.default.svc
  sources:
    - path: ''
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "9.5.14"
      chart: kube-prometheus
      helm:
        valueFiles:
          - $values/bitnami-kube-prometheus.values
    - repoURL: https://github.com/avk999/argocd
      targetRevision: HEAD
      ref: values
  project: default

