apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  ignoreDifferences:
  - kind: Ingress
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.7.3 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          global:
            nodeSelector:
              label-key1: "longhorn-true"
          metrics:
            serviceMonitor:
              enabled: true
          global:
            nodeSelector:
              longhorn: "true"
          defaultSettings:
            defaultReplicaCount: "2"
          persistence:
            defaultClassReplicaCount: "2"
          ingress: 
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-issuer
            ingressClassName: nginx
            host: longhorn.generated.world 
            tls: true 
            tlsSecret: longhorn.local-tls

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
