apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-v4f
  finalizers: []
spec:
  destination:
    name: ''
    namespace: v4f2
    server: https://kubernetes.default.svc
  sources:
    - path: ''
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 11.1.16
      chart: mysql
      helm:
        valueFiles:
          - $values/v4f-mysql-values.yaml
    - repoURL: https://github.com/avk999/argocd
      targetRevision: HEAD
      ref: values
  project: default

