apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - chart: open-webui
      repoURL:  https://helm.openwebui.com/
      targetRevision: 5.4.0
      helm:
        values: |
          image:
            tag: "v0.5.7"
          ollama:
            ollama:
              models:
                pull:
                  - hermes3:8b
                  - wizardlm2:7b
                  - deepseek-r1:14b
                  - hf.co/bartowski/Llama-3.2-3B-Instruct-uncensored-GGUF:Q8_0
                  - deepseek-coder-v2:latest
                  - mistral:7b
                  - codegemma:7b
                  - llama3.2-vision:latest
                  - phi3:3.8b
                  - llama3.2:latest
                  - deepseek-r1:7b
                  - hf.co/bartowski/Llama-3.2-3B-Instruct-GGUF:Q8_0
                  - gemma2:27b
                  - mistral:7b-instruct-fp16
                run:
                  - llama3.2:latest
                    #- mistral:7b-instruct-fp16
                    #                  - gemma2:27b
            persistentVolume:
              enabled: true 
              storageClass: "longhorn"
              size: 200Gi
            resources:
              requests:
                memory: 8192Mi
                cpu: 3500m
                  #              limits:
                  #  memory: 30Gi
                  #cpu: 5300m
            tolerations:
            - key: "dedicatedllm"
              operator: "Exists"
              effect: "PreferNoSchedule"

          ingress:
            enabled: true 
            class: nginx
            annotations:
               cert-manager.io/cluster-issuer: letsencrypt-issuer
               nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            host: ai.generated.world 
            tls: true
          persistence:
            storageClass: "longhorn"
    - repoURL: git@github.com:avk999/argocd.git
      targetRevision: master
      path: owui-extra-ingress 

  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
