apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - chart: open-webui
      repoURL:  https://helm.openwebui.com/
      targetRevision: 5.4.0
      helm:
        values: |
          ollama:
            ollama:
              models:
                pull:
                  - llama3.2
                  - phi3:3.8b
                  - llama3.2-vision
                  - mistral:7b
                  - codegemma:7b
                  - codegemma:2b
                run:
                  - llama3.2-vision
                    #- mistral:7b-instruct-fp16
                    #                  - gemma2:27b
            persistentVolume:
              enabled: true 
              storageClass: "longhorn"
              size: 100Gi
            resources:
              requests:
                memory: 8192Mi
                cpu: 4000m
              limits:
                memory: 30Gi
                cpu: 5300m

          ingress:
            enabled: true 
            class: nginx
            annotations:
               cert-manager.io/cluster-issuer: letsencrypt-issuer
               nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
            host: ai.generated.world 
            tls: true
          persistence:
            storageClass: "longhorn"


  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
