apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - chart: open-webui
      repoURL:  https://helm.openwebui.com/
      targetRevision: 5.4.0
      helm:
        values: |
          ollama:
            ollama:
              models:
                pull:
                  - llama3.2
                  - mistral
                run:
                  - llama3.2
                  - mistral
            persistentVolume:
              enabled: true 
              storageClass: "longhorn"
            resources:
              requests:
                memory: 8192Mi
                cpu: 4000m

          ingress:
            enabled: true 
            class: nginx
            annotations:
               cert-manager.io/cluster-issuer: letsencrypt-issuer
            host: ai.generated.world 
            tls: true
          persistence:
            storageClass: "longhorn"


  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
