apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syslog-ng
  namespace: argocd
spec:
  syncPolicy:
  project: default
  source :
    chart: syslog-ng
    repoURL:  https://avk999.github.io/charts
    targetRevision: "0.2.2"
    helm:
      values: |
        storage:
          storageClass: "longhorn"
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.1.109
        compressor:
          enabled: false
            #    - repoURL: git@github.com:avk999/argocd.git
            #      targetRevision: master
            #      path: syslog-ng-kust

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
