apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syslog-ng
  namespace: argocd
spec:
  syncPolicy:
  project: default
  sources:
    - chart: syslog-ng
      repoURL:  https://github.com/syslog-ng/syslog-ng/tree/master/contrib/syslog-ng-helm-chart
      targetRevision: "0.2"
      helm:
        values: |
          storage:
            storageClass: "longhorn"
          service:
            type: LoadBalancer
    - repoURL: git@github.com:avk999/argocd.git
      targetRevision: master
      path: syslog-ng-kust


  destination:
    server: https://kubernetes.default.svc
    namespace: logging
